config/routes.rb
Rails.application.routes.draw do
  get 'queries/index'
  devise_for :users
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :author, presence: true
end

app/models/query.rb
class Query < ApplicationRecord
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # request authentication to use the app
  before_action :authenticate_user!

  # require pagination for array
  require 'will_paginate/array'
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    # if there is a query, look for the word in the articles
    if params[:query].present?
      @articles = Article.where('lower(title) LIKE ?', "%#{params[:query].downcase}%")
      @articles |= Article.where('lower(content) LIKE ?', "%#{params[:query].downcase}%")
      @articles |= Article.where('lower(author) LIKE ?', "%#{params[:query].downcase}%")

      # function to add a query or edit the last query
      create_query(params[:query].downcase, params[:save])
    else
      @articles = Article.all
    end

    @articles = @articles.paginate(page: params[:page], per_page: 5)

    if turbo_frame_request?
      render partial: 'articles', locals: { articles: @articles }
    else
      render :index
    end
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :content, :author)
  end

  def create_query(query, save)
    # check if the query is more than 1 character long and
    # if one of the conditions defined in the search_bar_controller are met
    return unless query.length >= 1 && save == 'true'

    # check if the last query was made within 10 seconds
    # add to the database only if 10 seconds have already passed
    # since the last search
    last_query = Query.where(user_id: current_user.id).last
    return if last_query && (last_query.created_at - DateTime.now > -10)

    Query.create!(body: query, user_id: current_user.id)
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    # get queries from the current user, group them and count them
    @queries = Query.where(user_id: current_user.id).group(:body).order(count: :desc).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/articles/_article.html.erb
<div class="article-item container bg-dark bg-gradient p-3 rounded mb-3 shadow" id="<%= dom_id article %>">
    
  <h2 class="text-white mb-0"><%= article.title %></h2>
  <p class="text-white fst-italic">by <%= article.author %></p>

  <p class="text-white fs-5">
    <%= article.content %>
  </p>

  

</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles", class: "d-flex flex-column" do %>
  <%= render articles %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>

  <%= form_with(url: articles_path, method: :get, data: { controller: "search-bar", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
    <div class="d-flex my-4 gap-2">
        <%= form.text_field :query, data: { action: "input->search-bar#search focusout->search-bar#focusOut keyup->search-bar#keyPress"}, class: "form-control" %>
        
        <%= form.hidden_field :save, id: "save-input", value: false %>
        <%= form.submit "Search", class: "btn btn-primary" %>
    </div>
  <% end %>

  <div>
    <%= render "articles", articles: @articles %>
  </div>

  <%= will_paginate @articles, class: "container text-center fs-4" %>

  <%= link_to "New article", new_article_path, class: "btn btn-secondary my-3" %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Search Analytics", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Articles", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Analytics", queries_index_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Analytics</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/queries/index.html.erb
<div class="container">

  <div class="container my-5">
    <h2>Top 5 searches</h2>
    <%= bar_chart @queries.first(5)%>
  </div>

  <h1>Most searched</h1>

  <table class="table table-hover table-striped">
    <thead class="table-dark">
      <tr>
        <th>Query</th>
        <th>Instances</th>
      </tr>
    </thead>
    <tbody>
      <% @queries.each do |query| %>
        <tr>
          <th><%= query[0] %></th>
          <th><%= query[1] %></th>
        </tr>
      <% end %>
    </tbody>
  </table>


  
</div>